apiVersion: v2
name: opnsense2otel
description: Secure single-firewall OpenTelemetry and Prometheus observability for OPNsense
type: application
version: 0.1.0
appVersion: main
keywords:
  - opnsense
  - opentelemetry
  - otlp
  - prometheus
  - exporter
home: https://m7kni.io/opnsense2otel/
icon: https://m7kni.io/opnsense2otel/assets/project-icon-solid.svg
sources:
  - https://github.com/rknightion/opnsense2otel
maintainers:
  - name: rknightion
    email: rob@m7kni.io
    url: https://github.com/rknightion
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Documentation
      url: https://m7kni.io/opnsense2otel/
    - name: Getting started
      url: https://m7kni.io/opnsense2otel/getting-started/
    - name: Configuration reference
      url: https://m7kni.io/opnsense2otel/configuration/
    - name: source
      url: https://github.com/rknightion/opnsense2otel
  artifacthub.io/maintainers: |
    - name: rknightion
      email: rob@m7kni.io
